### ISSUE TITLE
could not decrypt key with given password

### ISSUE THREAD

**Issue by s1346520** [pego-labs/pego-chain#2]
start cmd:
geth  --config ./config.toml --datadir ./data  --syncmode full -unlock 0xe5B5E74cC1dBBE5f544F539607CEB4cc65adCdD2 --password ./data/keystore/pass.keystore --mine --allow-insecure-unlock  --port 30311 --verbosity 5 --cache 18000

error:
Fatal: Failed to unlock account 0xe5B5E74cC1dBBE5f544F539607CEB4cc65adCdD2 (could not decrypt key with given password)

keystore文件是通过imtoken钱包进行导出的. 该账户是否必须需要geth进行创建？

**Comment by pg-chain** [comment]
**--password** should be configured with the password which is used to encrypt the keystore file rather than the keystore file itself

**--password** 参量配置的是加密私钥时用的密码，并不是私钥json文件本身
