### ISSUE TITLE
按照搭建教程，p2p 网络连接不上

### ISSUE THREAD

**Issue by jwrookie** [pego-labs/pego-chain#3]
![image](https://github.com/pego-labs/pego-chain/assets/41732283/fb3085f7-bc6e-41ed-a471-9af4e4237857)

**Comment by pg-chain** [comment]
you may try to pull the latest config.toml and restart. The bootstrap node got max connection limit
可以试试拉去最新的config.toml 文件后，覆盖重启，原有的引导节点有连接上限，已经做过优化
